### PR TITLE
Update dependencies to work with Angular 16+

### PR DESCRIPTION
**Pull request by ovitrif**
Hey 👋🏻 !

First, many thanks for the work you've did on this!

I plan to use it in an Angular 16 project and faced some issues, so I proceeded to update its internal dependencies to work with Angular 16.

Apart from the main dependencies updates I also renamed the `projects` folder to `lib`, to make it a bit more consistent with the common naming conventions in open source repos.

Additionally, for those familiar with `nvm`, I added the config file to setup the expected node version for the project. Would've helped if you had it from then start, would've saved some headache fixing an initial set of errors 😅 .

I left it in a working state and decided to open a PR here.

Let me know what you think!

Kindly,
Ovi

### CODE REVIEW

**Comment by ovitrif** [comment]
Screenshot of the project running on Angular 16:

Arc 2023-10-01 000323

**Comment by deiv** [comment]
Hi @ovitrif ,

Thanks for your work. Looks good to me.

Before merging, its posible to change the project mayor version to 16.x.x (really 16.0.0) ? This way is more easy to match the library with the angular version :)

**Comment by ovitrif** [comment]
My pleasure!

I will do this change, it has crossed my mind as well 🫡, great to see how we both individually reached this conclusion that it would make versioning more meaningful if aligned with the Angular version number 🤗

**Comment by ovitrif** [comment]
Hey @deiv, updated the package version as you've requested 👍🏻 

Also added small info to the `README` on how to build the library project.

**Comment by deiv** [comment]
@ovitrif merged, thanks again !

**Comment by deiv** [comment]
@ovitrif

FYI: late, but ... have published the new version (16.0.1) in NPM (https://www.npmjs.com/package/ngx-markdown-it/v/16.0.1).

**Comment by ovitrif** [comment]
Thank you, I can revert to use the lib instead of my local one 🤙

**Pull request merged**
